---
deploy_tempest: true
tempest_test_type: "smoke"
tempest_test_args:
  smoke:  "--smoke"
  all: "--regex '.*'"
tempest_workers: 4
tempest_enable_cinder_service: true
tempest_enable_glance_service: true
tempest_enable_nova_service: true
tempest_enable_neutron_service: true
openstack_external_network_name: "public"
openstack_external_subnet_name: "public-subnet"
openstack_project_network_cidr: "172.0.4.0/24"
